Branch api
kstaats/karoo_gp pull request #70
Opened 2022-06-14 09:51 UTC by granawkins

This is the second of (now 3) big PRs; the first was `component-api`, the next will be `engine-api`. 

In this one:
- Add `Functions` and `Terminals` as classes. They both have a `.get()` method which returns a list of the active nodes. This can include constants (for terminals), and will support logical operators by returning situation-specific functions with `Operators.get(**kwargs)`.

- Add recursive `Branch` class. `Tree` is a wrapper for the the 'root' branch, stored in `tree.root`.

- Redo evolve methods to work with `Branch`. Evolution now uses a combination of `Population` methods (fitness_gene_pool, tournament) and `Tree` methods (copy, point_mutate, branch_mutate, crossover).

2022-06-15 12:02 UTC, ezio-melotti requested changes

2022-06-15 12:02 UTC, ezio-melotti commented on karoo_gp/branch.py
> +        """Print a heirarchical tree representation of all nodes
```suggestion
        """Print a hierarchical tree representation of all nodes
```

2022-06-15 13:52 UTC, granawkins commented
Dev call 15-June:

1. Grant will fix the open comments
2. Resubmit PR, Ezio approve
3. Grant submit tiny PR with 3 changes and updated test results:
  - sigfig rounding
  - round classify outputs to 6 digits
  - replace tf.divide with tf.divide_no_nan
4. Grant submit `engine-api` with (updated) tests passing.

2022-06-16 06:09 UTC, ezio-melotti approved these changes

2022-06-16 06:10 UTC, merged